// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Sentiment_AnalysisML.Model
{
    public class ModelInput
    {
        [ColumnName("comment"), LoadColumn(0)]
        public string Comment { get; set; }


        [ColumnName("Label"), LoadColumn(1)]
        public bool Label { get; set; }


    }
}
